# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
import os
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
                            QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QCheckBox, QFrame,
                               QGraphicsView, QLabel, QLineEdit, QPushButton,
                               QRadioButton, QSizePolicy, QSlider, QSpinBox,
                               QToolButton, QWidget, QGraphicsScene)

default_folder = u"C:/Users/%s/Desktop/test" % os.getlogin()


# self.scene = QGraphicsScene(Widget)
# self.stream_window = QGraphicsView(Widget)
# self.stream_window.setScene(self.scene)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(990, 910)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        self.stream_label = QLabel(Widget)
        self.stream_label.setObjectName(u"stream_label")
        self.stream_label.setGeometry(QRect(20, 10, 150, 22))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.stream_label.setFont(font)
        self.hardware_label = QLabel(Widget)
        self.hardware_label.setObjectName(u"hardware_label")
        self.hardware_label.setGeometry(QRect(20, 515, 150, 22))
        self.hardware_label.setFont(font)
        self.camera_label = QLabel(Widget)
        self.camera_label.setObjectName(u"camera_label")
        self.camera_label.setGeometry(QRect(20, 616, 150, 22))
        self.camera_label.setFont(font)
        self.stage_label = QLabel(Widget)
        self.stage_label.setObjectName(u"stage_label")
        self.stage_label.setGeometry(QRect(20, 745, 150, 22))
        self.stage_label.setFont(font)
        self.hardware_stage_button = QPushButton(Widget)
        self.hardware_stage_button.setObjectName(u"hardware_stage_button")
        self.hardware_stage_button.setGeometry(QRect(150, 550, 90, 25))
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.hardware_stage_button.sizePolicy().hasHeightForWidth())
        self.hardware_stage_button.setSizePolicy(sizePolicy1)
        self.hardware_stage_button.setAutoDefault(False)
        self.hardware_camera_button = QPushButton(Widget)
        self.hardware_camera_button.setObjectName(u"hardware_camera_button")
        self.hardware_camera_button.setGeometry(QRect(150, 580, 90, 25))
        self.hardware_dc4100_button = QPushButton(Widget)
        self.hardware_dc4100_button.setObjectName(u"hardware_dc4100_button")
        self.hardware_dc4100_button.setGeometry(QRect(360, 550, 90, 25))
        self.camera_exposure_slider = QSlider(Widget)
        self.camera_exposure_slider.setObjectName(u"camera_exposure_slider")
        self.camera_exposure_slider.setGeometry(QRect(150, 650, 191, 22))
        self.camera_exposure_slider.setTabletTracking(False)
        self.camera_exposure_slider.setAcceptDrops(False)
        self.camera_exposure_slider.setMinimum(50)
        self.camera_exposure_slider.setMaximum(166000)
        self.camera_exposure_slider.setValue(160000)
        self.camera_exposure_slider.setOrientation(Qt.Horizontal)
        self.camera_exposure_slider.setTickPosition(QSlider.TicksBelow)
        self.camera_exposure_slider.setTickInterval(10000)
        self.camera_gain_slider = QSlider(Widget)
        self.camera_gain_slider.setObjectName(u"camera_gain_slider")
        self.camera_gain_slider.setGeometry(QRect(150, 680, 191, 22))
        self.camera_gain_slider.setMaximum(48)
        self.camera_gain_slider.setValue(0)
        self.camera_gain_slider.setOrientation(Qt.Horizontal)
        self.camera_gain_slider.setTickPosition(QSlider.TicksBelow)
        self.camera_gain_slider.setTickInterval(1)
        self.camera_gamma_slider = QSlider(Widget)
        self.camera_gamma_slider.setObjectName(u"camera_gamma_slider")
        self.camera_gamma_slider.setGeometry(QRect(150, 710, 191, 22))
        self.camera_gamma_slider.setMinimum(2)
        self.camera_gamma_slider.setMaximum(20)
        self.camera_gamma_slider.setSingleStep(0)
        self.camera_gamma_slider.setValue(10)
        self.camera_gamma_slider.setOrientation(Qt.Horizontal)
        self.camera_gamma_slider.setTickPosition(QSlider.TicksBelow)
        self.camera_gamma_slider.setTickInterval(1)
        self.camera_capture_button = QPushButton(Widget)
        self.camera_capture_button.setObjectName(u"camera_capture_button")
        self.camera_capture_button.setGeometry(QRect(430, 680, 75, 24))
        self.stage_lensx_position = QLabel(Widget)
        self.stage_lensx_position.setObjectName(u"stage_lensx_position")
        self.stage_lensx_position.setGeometry(QRect(140, 780, 121, 21))
        self.stage_lensx_position.setAlignment(Qt.AlignCenter)
        self.stage_lensx_step_p = QToolButton(Widget)
        self.stage_lensx_step_p.setObjectName(u"stage_lensx_step_p")
        self.stage_lensx_step_p.setGeometry(QRect(380, 780, 22, 22))
        self.stage_lensx_step_p.setArrowType(Qt.RightArrow)
        self.stage_lensx_step_n = QToolButton(Widget)
        self.stage_lensx_step_n.setObjectName(u"stage_lensx_step_n")
        self.stage_lensx_step_n.setGeometry(QRect(270, 780, 22, 22))
        self.stage_lensx_step_n.setArrowType(Qt.LeftArrow)
        self.stage_lensx_move = QPushButton(Widget)
        self.stage_lensx_move.setObjectName(u"stage_lensx_move")
        self.stage_lensx_move.setGeometry(QRect(430, 780, 75, 24))
        self.stage_lensy_step_n = QToolButton(Widget)
        self.stage_lensy_step_n.setObjectName(u"stage_lensy_step_n")
        self.stage_lensy_step_n.setGeometry(QRect(270, 810, 22, 22))
        self.stage_lensy_step_n.setArrowType(Qt.LeftArrow)
        self.stage_lensy_position = QLabel(Widget)
        self.stage_lensy_position.setObjectName(u"stage_lensy_position")
        self.stage_lensy_position.setGeometry(QRect(140, 810, 121, 21))
        self.stage_lensy_position.setAlignment(Qt.AlignCenter)
        self.stage_lensy_move = QPushButton(Widget)
        self.stage_lensy_move.setObjectName(u"stage_lensy_move")
        self.stage_lensy_move.setGeometry(QRect(430, 810, 75, 24))
        self.stage_lensy_step_p = QToolButton(Widget)
        self.stage_lensy_step_p.setObjectName(u"stage_lensy_step_p")
        self.stage_lensy_step_p.setGeometry(QRect(380, 810, 22, 22))
        self.stage_lensy_step_p.setArrowType(Qt.RightArrow)
        self.stage_lensz_step_n = QToolButton(Widget)
        self.stage_lensz_step_n.setObjectName(u"stage_lensz_step_n")
        self.stage_lensz_step_n.setGeometry(QRect(270, 840, 22, 22))
        self.stage_lensz_step_n.setArrowType(Qt.LeftArrow)
        self.stage_lensz_position = QLabel(Widget)
        self.stage_lensz_position.setObjectName(u"stage_lensz_position")
        self.stage_lensz_position.setGeometry(QRect(140, 840, 121, 21))
        self.stage_lensz_position.setAlignment(Qt.AlignCenter)
        self.stage_lensz_move = QPushButton(Widget)
        self.stage_lensz_move.setObjectName(u"stage_lensz_move")
        self.stage_lensz_move.setGeometry(QRect(430, 840, 75, 24))
        self.stage_lensz_step_p = QToolButton(Widget)
        self.stage_lensz_step_p.setObjectName(u"stage_lensz_step_p")
        self.stage_lensz_step_p.setGeometry(QRect(380, 840, 22, 22))
        self.stage_lensz_step_p.setArrowType(Qt.RightArrow)
        self.stage_camz_step_n = QToolButton(Widget)
        self.stage_camz_step_n.setObjectName(u"stage_camz_step_n")
        self.stage_camz_step_n.setGeometry(QRect(270, 870, 22, 22))
        self.stage_camz_step_n.setArrowType(Qt.LeftArrow)
        self.stage_camz_position = QLabel(Widget)
        self.stage_camz_position.setObjectName(u"stage_camz_position")
        self.stage_camz_position.setGeometry(QRect(140, 870, 121, 21))
        self.stage_camz_position.setAlignment(Qt.AlignCenter)
        self.stage_camz_move = QPushButton(Widget)
        self.stage_camz_move.setObjectName(u"stage_camz_move")
        self.stage_camz_move.setGeometry(QRect(430, 870, 75, 24))
        self.stage_camz_step_p = QToolButton(Widget)
        self.stage_camz_step_p.setObjectName(u"stage_camz_step_p")
        self.stage_camz_step_p.setGeometry(QRect(380, 870, 22, 22))
        self.stage_camz_step_p.setArrowType(Qt.RightArrow)
        self.line = QFrame(Widget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(520, 10, 20, 891))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.alignment_label = QLabel(Widget)
        self.alignment_label.setObjectName(u"alignment_label")
        self.alignment_label.setGeometry(QRect(550, 10, 150, 22))
        self.alignment_label.setFont(font)
        self.alignment_folder_label = QLabel(Widget)
        self.alignment_folder_label.setObjectName(u"alignment_folder_label")
        self.alignment_folder_label.setGeometry(QRect(550, 40, 120, 20))
        self.alignment_folder_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.alignment_start_button = QPushButton(Widget)
        self.alignment_start_button.setObjectName(u"alignment_start_button")
        self.alignment_start_button.setGeometry(QRect(690, 100, 75, 25))
        self.alignment_abort_button = QPushButton(Widget)
        self.alignment_abort_button.setObjectName(u"alignment_abort_button")
        self.alignment_abort_button.setEnabled(False)
        self.alignment_abort_button.setGeometry(QRect(770, 100, 75, 25))
        self.alignment_abort_button.setFlat(False)
        self.roi_label = QLabel(Widget)
        self.roi_label.setObjectName(u"roi_label")
        self.roi_label.setGeometry(QRect(550, 140, 150, 22))
        self.roi_label.setFont(font)
        self.led_label = QLabel(Widget)
        self.led_label.setObjectName(u"led_label")
        self.led_label.setGeometry(QRect(550, 290, 150, 22))
        self.led_label.setFont(font)
        self.centers_label = QLabel(Widget)
        self.centers_label.setObjectName(u"centers_label")
        self.centers_label.setGeometry(QRect(550, 420, 150, 22))
        self.centers_label.setFont(font)
        self.roi_center_label = QLabel(Widget)
        self.roi_center_label.setObjectName(u"roi_center_label")
        self.roi_center_label.setGeometry(QRect(550, 170, 120, 21))
        self.roi_center_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.roi_range_label = QLabel(Widget)
        self.roi_range_label.setObjectName(u"roi_range_label")
        self.roi_range_label.setGeometry(QRect(550, 200, 120, 21))
        self.roi_range_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.roi_threshold_label = QLabel(Widget)
        self.roi_threshold_label.setObjectName(u"roi_threshold_label")
        self.roi_threshold_label.setGeometry(QRect(550, 230, 120, 21))
        self.roi_threshold_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.roi_center_spin_x = QSpinBox(Widget)
        self.roi_center_spin_x.setObjectName(u"roi_center_spin_x")
        self.roi_center_spin_x.setGeometry(QRect(690, 170, 75, 22))
        self.roi_center_spin_x.setMaximum(4428)
        self.roi_center_spin_x.setValue(2000)
        self.roi_center_spin_y = QSpinBox(Widget)
        self.roi_center_spin_y.setObjectName(u"roi_center_spin_y")
        self.roi_center_spin_y.setGeometry(QRect(770, 170, 75, 22))
        self.roi_center_spin_y.setMaximum(4416)
        self.roi_center_spin_y.setValue(2000)
        self.roi_pxl1_label = QLabel(Widget)
        self.roi_pxl1_label.setObjectName(u"roi_pxl1_label")
        self.roi_pxl1_label.setGeometry(QRect(850, 170, 30, 20))
        self.roi_pxl1_label.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.roi_range_spin_min = QSpinBox(Widget)
        self.roi_range_spin_min.setObjectName(u"roi_range_spin_min")
        self.roi_range_spin_min.setGeometry(QRect(690, 200, 75, 22))
        self.roi_range_spin_min.setMaximum(4999)
        self.roi_range_spin_max = QSpinBox(Widget)
        self.roi_range_spin_max.setObjectName(u"roi_range_spin_max")
        self.roi_range_spin_max.setGeometry(QRect(770, 200, 75, 22))
        self.roi_range_spin_max.setMaximum(5000)
        self.roi_range_spin_max.setValue(4000)
        self.roi_threshold_spin = QSpinBox(Widget)
        self.roi_threshold_spin.setObjectName(u"roi_threshold_spin")
        self.roi_threshold_spin.setGeometry(QRect(690, 230, 75, 22))
        self.roi_threshold_spin.setMaximum(255)
        self.roi_cpc_check = QCheckBox(Widget)
        self.roi_cpc_check.setObjectName(u"roi_cpc_check")
        self.roi_cpc_check.setGeometry(QRect(690, 260, 151, 20))
        self.roi_cpc_check.setChecked(True)
        self.led_red_enable_check = QCheckBox(Widget)
        self.led_red_enable_check.setObjectName(u"led_red_enable_check")
        self.led_red_enable_check.setGeometry(QRect(690, 320, 71, 20))
        self.led_red_label = QLabel(Widget)
        self.led_red_label.setObjectName(u"led_red_label")
        self.led_red_label.setGeometry(QRect(550, 320, 120, 21))
        self.led_red_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.led_red_current_spin = QSpinBox(Widget)
        self.led_red_current_spin.setObjectName(u"led_red_current_spin")
        self.led_red_current_spin.setGeometry(QRect(770, 320, 75, 22))
        self.led_red_current_spin.setMaximum(1000)
        self.led_red_current_spin.setValue(0)
        self.roi_pxl2_label = QLabel(Widget)
        self.roi_pxl2_label.setObjectName(u"roi_pxl2_label")
        self.roi_pxl2_label.setGeometry(QRect(850, 200, 30, 20))
        self.roi_pxl2_label.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.led_ma1_label = QLabel(Widget)
        self.led_ma1_label.setObjectName(u"led_ma1_label")
        self.led_ma1_label.setGeometry(QRect(850, 320, 30, 20))
        self.led_ma1_label.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.led_green_label = QLabel(Widget)
        self.led_green_label.setObjectName(u"led_green_label")
        self.led_green_label.setGeometry(QRect(550, 350, 120, 21))
        self.led_green_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.led_green_enable_check = QCheckBox(Widget)
        self.led_green_enable_check.setObjectName(u"led_green_enable_check")
        self.led_green_enable_check.setGeometry(QRect(690, 350, 71, 20))
        self.led_green_current_spin = QSpinBox(Widget)
        self.led_green_current_spin.setObjectName(u"led_green_current_spin")
        self.led_green_current_spin.setGeometry(QRect(770, 350, 75, 22))
        self.led_green_current_spin.setMaximum(1000)
        self.led_green_current_spin.setValue(0)
        self.led_ma2_label = QLabel(Widget)
        self.led_ma2_label.setObjectName(u"led_ma2_label")
        self.led_ma2_label.setGeometry(QRect(850, 350, 30, 20))
        self.led_ma2_label.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.led_ir_label = QLabel(Widget)
        self.led_ir_label.setObjectName(u"led_ir_label")
        self.led_ir_label.setGeometry(QRect(550, 380, 120, 21))
        self.led_ir_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.led_ir_enable_check = QCheckBox(Widget)
        self.led_ir_enable_check.setObjectName(u"led_ir_enable_check")
        self.led_ir_enable_check.setGeometry(QRect(690, 380, 71, 20))
        self.led_ir_current_spin = QSpinBox(Widget)
        self.led_ir_current_spin.setObjectName(u"led_ir_current_spin")
        self.led_ir_current_spin.setGeometry(QRect(770, 380, 75, 22))
        self.led_ir_current_spin.setMaximum(1000)
        self.led_ir_current_spin.setValue(0)
        self.led_ma3_label = QLabel(Widget)
        self.led_ma3_label.setObjectName(u"led_ma3_label")
        self.led_ma3_label.setGeometry(QRect(850, 380, 30, 20))
        self.led_ma3_label.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.hardware_stage_label = QLabel(Widget)
        self.hardware_stage_label.setObjectName(u"hardware_stage_label")
        self.hardware_stage_label.setGeometry(QRect(20, 550, 120, 20))
        self.hardware_stage_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.hardware_camera_label = QLabel(Widget)
        self.hardware_camera_label.setObjectName(u"hardware_camera_label")
        self.hardware_camera_label.setGeometry(QRect(20, 580, 120, 20))
        self.hardware_camera_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.hardware_dc4100_label = QLabel(Widget)
        self.hardware_dc4100_label.setObjectName(u"hardware_dc4100_label")
        self.hardware_dc4100_label.setGeometry(QRect(260, 550, 90, 25))
        self.hardware_dc4100_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.camera_exposure_label = QLabel(Widget)
        self.camera_exposure_label.setObjectName(u"camera_exposure_label")
        self.camera_exposure_label.setGeometry(QRect(20, 650, 120, 21))
        self.camera_exposure_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.camera_gamma_label = QLabel(Widget)
        self.camera_gamma_label.setObjectName(u"camera_gamma_label")
        self.camera_gamma_label.setGeometry(QRect(20, 710, 120, 21))
        self.camera_gamma_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.camera_gain_label = QLabel(Widget)
        self.camera_gain_label.setObjectName(u"camera_gain_label")
        self.camera_gain_label.setGeometry(QRect(20, 680, 120, 21))
        self.camera_gain_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.stage_lensx_label = QLabel(Widget)
        self.stage_lensx_label.setObjectName(u"stage_lensx_label")
        self.stage_lensx_label.setGeometry(QRect(20, 780, 120, 21))
        self.stage_lensx_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.stage_lensy_label = QLabel(Widget)
        self.stage_lensy_label.setObjectName(u"stage_lensy_label")
        self.stage_lensy_label.setGeometry(QRect(20, 810, 120, 21))
        self.stage_lensy_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.stage_lensz_label = QLabel(Widget)
        self.stage_lensz_label.setObjectName(u"stage_lensz_label")
        self.stage_lensz_label.setGeometry(QRect(20, 840, 120, 21))
        self.stage_lensz_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.stage_camz_label = QLabel(Widget)
        self.stage_camz_label.setObjectName(u"stage_camz_label")
        self.stage_camz_label.setGeometry(QRect(20, 870, 120, 21))
        self.stage_camz_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_l1_label = QLabel(Widget)
        self.centers_l1_label.setObjectName(u"centers_l1_label")
        self.centers_l1_label.setGeometry(QRect(550, 450, 120, 21))
        self.centers_l1_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_l1_pos_label = QLabel(Widget)
        self.centers_l1_pos_label.setObjectName(u"centers_l1_pos_label")
        self.centers_l1_pos_label.setGeometry(QRect(680, 450, 80, 20))
        self.centers_l1_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_l1_ok_button = QPushButton(Widget)
        self.centers_l1_ok_button.setObjectName(u"centers_l1_ok_button")
        self.centers_l1_ok_button.setEnabled(False)
        self.centers_l1_ok_button.setGeometry(QRect(770, 450, 75, 25))
        self.centers_l2_pos_label = QLabel(Widget)
        self.centers_l2_pos_label.setObjectName(u"centers_l2_pos_label")
        self.centers_l2_pos_label.setGeometry(QRect(680, 480, 80, 20))
        self.centers_l2_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_l2_ok_button = QPushButton(Widget)
        self.centers_l2_ok_button.setObjectName(u"centers_l2_ok_button")
        self.centers_l2_ok_button.setEnabled(False)
        self.centers_l2_ok_button.setGeometry(QRect(770, 480, 75, 25))
        self.centers_l2_label = QLabel(Widget)
        self.centers_l2_label.setObjectName(u"centers_l2_label")
        self.centers_l2_label.setGeometry(QRect(550, 480, 120, 21))
        self.centers_l2_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_correction_pos_label = QLabel(Widget)
        self.centers_correction_pos_label.setObjectName(u"centers_correction_pos_label")
        self.centers_correction_pos_label.setGeometry(QRect(680, 510, 91, 20))
        self.centers_correction_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_correction_move_button = QPushButton(Widget)
        self.centers_correction_move_button.setObjectName(u"centers_correction_move_button")
        self.centers_correction_move_button.setEnabled(False)
        self.centers_correction_move_button.setGeometry(QRect(770, 510, 75, 25))
        self.centers_correction_label = QLabel(Widget)
        self.centers_correction_label.setObjectName(u"centers_correction_label")
        self.centers_correction_label.setGeometry(QRect(550, 510, 120, 21))
        self.centers_correction_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_rcpc_pos_label = QLabel(Widget)
        self.centers_rcpc_pos_label.setObjectName(u"centers_rcpc_pos_label")
        self.centers_rcpc_pos_label.setGeometry(QRect(680, 560, 81, 20))
        self.centers_rcpc_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_rcpc_label = QLabel(Widget)
        self.centers_rcpc_label.setObjectName(u"centers_rcpc_label")
        self.centers_rcpc_label.setGeometry(QRect(550, 560, 120, 21))
        self.centers_rcpc_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_gcpc_pos_label = QLabel(Widget)
        self.centers_gcpc_pos_label.setObjectName(u"centers_gcpc_pos_label")
        self.centers_gcpc_pos_label.setGeometry(QRect(680, 590, 81, 20))
        self.centers_gcpc_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_cpc_ok_button = QPushButton(Widget)
        self.centers_cpc_ok_button.setObjectName(u"centers_cpc_ok_button")
        self.centers_cpc_ok_button.setEnabled(False)
        self.centers_cpc_ok_button.setGeometry(QRect(770, 590, 75, 25))
        self.centers_gcpc_label = QLabel(Widget)
        self.centers_gcpc_label.setObjectName(u"centers_gcpc_label")
        self.centers_gcpc_label.setGeometry(QRect(550, 590, 120, 21))
        self.centers_gcpc_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_bcpc_pos_label = QLabel(Widget)
        self.centers_bcpc_pos_label.setObjectName(u"centers_bcpc_pos_label")
        self.centers_bcpc_pos_label.setGeometry(QRect(680, 620, 80, 20))
        self.centers_bcpc_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_bcpc_label = QLabel(Widget)
        self.centers_bcpc_label.setObjectName(u"centers_bcpc_label")
        self.centers_bcpc_label.setGeometry(QRect(550, 620, 120, 21))
        self.centers_bcpc_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_ricg_pos_label = QLabel(Widget)
        self.centers_ricg_pos_label.setObjectName(u"centers_ricg_pos_label")
        self.centers_ricg_pos_label.setGeometry(QRect(680, 660, 80, 20))
        self.centers_ricg_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_ricg_label = QLabel(Widget)
        self.centers_ricg_label.setObjectName(u"centers_ricg_label")
        self.centers_ricg_label.setGeometry(QRect(550, 660, 120, 21))
        self.centers_ricg_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_gicg_pos_label = QLabel(Widget)
        self.centers_gicg_pos_label.setObjectName(u"centers_gicg_pos_label")
        self.centers_gicg_pos_label.setGeometry(QRect(680, 690, 81, 20))
        self.centers_gicg_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_icg_ok_button = QPushButton(Widget)
        self.centers_icg_ok_button.setObjectName(u"centers_icg_ok_button")
        self.centers_icg_ok_button.setEnabled(False)
        self.centers_icg_ok_button.setGeometry(QRect(770, 690, 75, 25))
        self.centers_gicg_label = QLabel(Widget)
        self.centers_gicg_label.setObjectName(u"centers_gicg_label")
        self.centers_gicg_label.setGeometry(QRect(550, 690, 120, 21))
        self.centers_gicg_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_bicg_pos_label = QLabel(Widget)
        self.centers_bicg_pos_label.setObjectName(u"centers_bicg_pos_label")
        self.centers_bicg_pos_label.setGeometry(QRect(680, 720, 81, 20))
        self.centers_bicg_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_bicg_label = QLabel(Widget)
        self.centers_bicg_label.setObjectName(u"centers_bicg_label")
        self.centers_bicg_label.setGeometry(QRect(550, 720, 120, 21))
        self.centers_bicg_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_rdelta_pos_label = QLabel(Widget)
        self.centers_rdelta_pos_label.setObjectName(u"centers_rdelta_pos_label")
        self.centers_rdelta_pos_label.setGeometry(QRect(680, 760, 91, 20))
        self.centers_rdelta_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_gdelta_pos_label = QLabel(Widget)
        self.centers_gdelta_pos_label.setObjectName(u"centers_gdelta_pos_label")
        self.centers_gdelta_pos_label.setGeometry(QRect(680, 790, 91, 20))
        self.centers_gdelta_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_rdelta_label = QLabel(Widget)
        self.centers_rdelta_label.setObjectName(u"centers_rdelta_label")
        self.centers_rdelta_label.setGeometry(QRect(550, 760, 120, 21))
        self.centers_rdelta_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_bdelta_pos_label = QLabel(Widget)
        self.centers_bdelta_pos_label.setObjectName(u"centers_bdelta_pos_label")
        self.centers_bdelta_pos_label.setGeometry(QRect(680, 820, 91, 20))
        self.centers_bdelta_pos_label.setAlignment(Qt.AlignCenter)
        self.centers_bdelta_label = QLabel(Widget)
        self.centers_bdelta_label.setObjectName(u"centers_bdelta_label")
        self.centers_bdelta_label.setGeometry(QRect(550, 820, 120, 21))
        self.centers_bdelta_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.centers_gdelta_label = QLabel(Widget)
        self.centers_gdelta_label.setObjectName(u"centers_gdelta_label")
        self.centers_gdelta_label.setGeometry(QRect(550, 790, 120, 21))
        self.centers_gdelta_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.alignment_folder_button = QToolButton(Widget)
        self.alignment_folder_button.setObjectName(u"alignment_folder_button")
        self.alignment_folder_button.setGeometry(QRect(950, 40, 22, 22))
        self.camera_exposure_val_label = QLabel(Widget)
        self.camera_exposure_val_label.setObjectName(u"camera_exposure_val_label")
        self.camera_exposure_val_label.setGeometry(QRect(350, 650, 61, 21))
        self.camera_exposure_val_label.setAlignment(Qt.AlignCenter)
        self.camera_gain_val_label = QLabel(Widget)
        self.camera_gain_val_label.setObjectName(u"camera_gain_val_label")
        self.camera_gain_val_label.setGeometry(QRect(350, 680, 61, 21))
        self.camera_gain_val_label.setAlignment(Qt.AlignCenter)
        self.camera_gamma_val_label = QLabel(Widget)
        self.camera_gamma_val_label.setObjectName(u"camera_gamma_val_label")
        self.camera_gamma_val_label.setGeometry(QRect(350, 710, 61, 21))
        self.camera_gamma_val_label.setAlignment(Qt.AlignCenter)
        self.stage_lensx_entry = QLineEdit(Widget)
        self.stage_lensx_entry.setObjectName(u"stage_lensx_entry")
        self.stage_lensx_entry.setGeometry(QRect(300, 780, 70, 20))
        self.stage_lensx_entry.setAlignment(Qt.AlignCenter)
        self.stage_lensz_entry = QLineEdit(Widget)
        self.stage_lensz_entry.setObjectName(u"stage_lensz_entry")
        self.stage_lensz_entry.setGeometry(QRect(300, 840, 70, 20))
        self.stage_lensz_entry.setAlignment(Qt.AlignCenter)
        self.stage_camz_entry = QLineEdit(Widget)
        self.stage_camz_entry.setObjectName(u"stage_camz_entry")
        self.stage_camz_entry.setGeometry(QRect(300, 870, 70, 20))
        self.stage_camz_entry.setAlignment(Qt.AlignCenter)
        self.stage_lensy_entry = QLineEdit(Widget)
        self.stage_lensy_entry.setObjectName(u"stage_lensy_entry")
        self.stage_lensy_entry.setGeometry(QRect(300, 810, 70, 20))
        self.stage_lensy_entry.setAlignment(Qt.AlignCenter)
        self.alignment_folder_entry = QLineEdit(Widget)
        self.alignment_folder_entry.setObjectName(u"alignment_folder_entry")
        self.alignment_folder_entry.setGeometry(QRect(690, 40, 250, 22))
        self.alignment_folder_entry.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.hardware_stage_indicator = QRadioButton(Widget)
        self.hardware_stage_indicator.setObjectName(u"hardware_stage_indicator")
        self.hardware_stage_indicator.setGeometry(QRect(240, 550, 16, 20))
        self.hardware_stage_indicator.setCursor(QCursor(Qt.ForbiddenCursor))
        self.hardware_stage_indicator.setFocusPolicy(Qt.StrongFocus)
        self.hardware_stage_indicator.setLayoutDirection(Qt.RightToLeft)
        self.hardware_stage_indicator.setAutoFillBackground(False)
        self.hardware_stage_indicator.setStyleSheet(u"QRadioButton::indicator{background-color : gray}")
        self.hardware_stage_indicator.setCheckable(False)
        self.hardware_stage_indicator.setAutoExclusive(True)
        self.hardware_camera_indicator = QRadioButton(Widget)
        self.hardware_camera_indicator.setObjectName(u"hardware_camera_indicator")
        self.hardware_camera_indicator.setGeometry(QRect(240, 580, 16, 20))
        self.hardware_camera_indicator.setCursor(QCursor(Qt.ForbiddenCursor))
        self.hardware_camera_indicator.setFocusPolicy(Qt.StrongFocus)
        self.hardware_camera_indicator.setLayoutDirection(Qt.RightToLeft)
        self.hardware_camera_indicator.setAutoFillBackground(False)
        self.hardware_camera_indicator.setStyleSheet(u"QRadioButton::indicator{background-color : gray}")
        self.hardware_camera_indicator.setCheckable(False)
        self.hardware_camera_indicator.setAutoExclusive(True)
        self.hardware_dc4100_indicator = QRadioButton(Widget)
        self.hardware_dc4100_indicator.setObjectName(u"hardware_dc4100_indicator")
        self.hardware_dc4100_indicator.setGeometry(QRect(450, 550, 16, 20))
        self.hardware_dc4100_indicator.setCursor(QCursor(Qt.ForbiddenCursor))
        self.hardware_dc4100_indicator.setFocusPolicy(Qt.StrongFocus)
        self.hardware_dc4100_indicator.setLayoutDirection(Qt.RightToLeft)
        self.hardware_dc4100_indicator.setAutoFillBackground(False)
        self.hardware_dc4100_indicator.setStyleSheet(u"QRadioButton::indicator{background-color : gray}")
        self.hardware_dc4100_indicator.setCheckable(False)
        self.hardware_dc4100_indicator.setAutoExclusive(True)
        self.alignment_sn_entry = QLineEdit(Widget)
        self.alignment_sn_entry.setObjectName(u"alignment_sn_entry")
        self.alignment_sn_entry.setGeometry(QRect(690, 70, 155, 22))
        self.alignment_sn_label = QLabel(Widget)
        self.alignment_sn_label.setObjectName(u"alignment_sn_label")
        self.alignment_sn_label.setGeometry(QRect(550, 70, 120, 20))
        self.alignment_sn_label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)

        self.stream_window = QGraphicsView(Widget)

        self.stream_window.setObjectName(u"stream_window")
        self.stream_window.setGeometry(QRect(30, 40, 461, 462))
        sizePolicy.setHeightForWidth(self.stream_window.sizePolicy().hasHeightForWidth())
        self.stream_window.setSizePolicy(sizePolicy)
        self.stream_window.setMouseTracking(True)
        self.stream_window.setAutoFillBackground(False)
        self.stream_window.setFocusPolicy(Qt.NoFocus)
        self.stream_window.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.stream_window.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.stream_window.verticalScrollBar().setEnabled(False)
        self.stream_window.horizontalScrollBar().setEnabled(False)
        self.stream_window.setDragMode(QGraphicsView.ScrollHandDrag)
        self.stream_window.setTransformationAnchor(QGraphicsView.AnchorUnderMouse)
        self.stream_window.setResizeAnchor(QGraphicsView.AnchorUnderMouse)
        self.scene = QGraphicsScene(Widget)
        self.stream_window.setScene(self.scene)

        self.retranslateUi(Widget)

        self.hardware_stage_button.setDefault(False)
        self.alignment_abort_button.setDefault(False)

        QMetaObject.connectSlotsByName(Widget)

    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"GUI Example", None))
        self.stream_label.setText(QCoreApplication.translate("Widget", u"Live Stream", None))
        self.hardware_label.setText(QCoreApplication.translate("Widget", u"Hardware", None))
        self.camera_label.setText(QCoreApplication.translate("Widget", u"Camera Controls", None))
        self.stage_label.setText(QCoreApplication.translate("Widget", u"Stage Controls", None))
        self.hardware_stage_button.setText(QCoreApplication.translate("Widget", u"Connect/Close", None))
        self.hardware_camera_button.setText(QCoreApplication.translate("Widget", u"Connect/Close", None))
        self.hardware_dc4100_button.setText(QCoreApplication.translate("Widget", u"Connect/Close", None))
        self.camera_capture_button.setText(QCoreApplication.translate("Widget", u"Capture!", None))
        self.stage_lensx_position.setText(QCoreApplication.translate("Widget", u"0.000000 (mm)", None))
        self.stage_lensx_step_p.setText(QCoreApplication.translate("Widget", u"...", None))
        self.stage_lensx_step_n.setText(QCoreApplication.translate("Widget", u"...", None))
        self.stage_lensx_move.setText(QCoreApplication.translate("Widget", u"ABS Move", None))
        self.stage_lensy_step_n.setText(QCoreApplication.translate("Widget", u"...", None))
        self.stage_lensy_position.setText(QCoreApplication.translate("Widget", u"0.000000 (mm)", None))
        self.stage_lensy_move.setText(QCoreApplication.translate("Widget", u"ABS Move", None))
        self.stage_lensy_step_p.setText(QCoreApplication.translate("Widget", u"...", None))
        self.stage_lensz_step_n.setText(QCoreApplication.translate("Widget", u"...", None))
        self.stage_lensz_position.setText(QCoreApplication.translate("Widget", u"0.000000 (mm)", None))
        self.stage_lensz_move.setText(QCoreApplication.translate("Widget", u"ABS Move", None))
        self.stage_lensz_step_p.setText(QCoreApplication.translate("Widget", u"...", None))
        self.stage_camz_step_n.setText(QCoreApplication.translate("Widget", u"...", None))
        self.stage_camz_position.setText(QCoreApplication.translate("Widget", u"0.000000 (mm)", None))
        self.stage_camz_move.setText(QCoreApplication.translate("Widget", u"ABS Move", None))
        self.stage_camz_step_p.setText(QCoreApplication.translate("Widget", u"...", None))
        self.alignment_label.setText(QCoreApplication.translate("Widget", u"Alignment Routine", None))
        self.alignment_folder_label.setText(QCoreApplication.translate("Widget", u"Results Folder:", None))
        self.alignment_start_button.setText(QCoreApplication.translate("Widget", u"START", None))
        self.alignment_abort_button.setText(QCoreApplication.translate("Widget", u"ABORT", None))
        self.roi_label.setText(QCoreApplication.translate("Widget", u"ROI Settings", None))
        self.led_label.setText(QCoreApplication.translate("Widget", u"LED Driver Settings", None))
        self.centers_label.setText(QCoreApplication.translate("Widget", u"Detected Centers", None))
        self.roi_center_label.setText(QCoreApplication.translate("Widget", u"ROI Center (x, y):", None))
        self.roi_range_label.setText(QCoreApplication.translate("Widget", u"ROI (min, max):", None))
        self.roi_threshold_label.setText(QCoreApplication.translate("Widget", u"Threshold:", None))
        self.roi_pxl1_label.setText(QCoreApplication.translate("Widget", u"(pxl)", None))
        self.roi_cpc_check.setText(QCoreApplication.translate("Widget", u"Detect CPCs", None))
        self.led_red_enable_check.setText(QCoreApplication.translate("Widget", u"On/Off", None))
        self.led_red_label.setText(QCoreApplication.translate("Widget", u"Red (625 nm):", None))
        self.roi_pxl2_label.setText(QCoreApplication.translate("Widget", u"(pxl)", None))
        self.led_ma1_label.setText(QCoreApplication.translate("Widget", u"(mA)", None))
        self.led_green_label.setText(QCoreApplication.translate("Widget", u"Green (530 nm):", None))
        self.led_green_enable_check.setText(QCoreApplication.translate("Widget", u"On/Off", None))
        self.led_ma2_label.setText(QCoreApplication.translate("Widget", u"(mA)", None))
        self.led_ir_label.setText(QCoreApplication.translate("Widget", u"Infrared:", None))
        self.led_ir_enable_check.setText(QCoreApplication.translate("Widget", u"On/Off", None))
        self.led_ma3_label.setText(QCoreApplication.translate("Widget", u"(mA)", None))
        self.hardware_stage_label.setText(QCoreApplication.translate("Widget", u"PI Stage:", None))
        self.hardware_camera_label.setText(QCoreApplication.translate("Widget", u"Atlas Camera:", None))
        self.hardware_dc4100_label.setText(QCoreApplication.translate("Widget", u"DC4100 (1):", None))
        self.camera_exposure_label.setText(QCoreApplication.translate("Widget", u"Exposure (us):", None))
        self.camera_gamma_label.setText(QCoreApplication.translate("Widget", u"Gamma:", None))
        self.camera_gain_label.setText(QCoreApplication.translate("Widget", u"Gain (dB):", None))
        self.stage_lensx_label.setText(QCoreApplication.translate("Widget", u"Lens X (mm):", None))
        self.stage_lensy_label.setText(QCoreApplication.translate("Widget", u"Lens Y (mm):", None))
        self.stage_lensz_label.setText(QCoreApplication.translate("Widget", u"Lens Z (mm):", None))
        self.stage_camz_label.setText(QCoreApplication.translate("Widget", u"Cam. Z (mm):", None))
        self.centers_l1_label.setText(QCoreApplication.translate("Widget", u"Lens Barrel (L1):", None))
        self.centers_l1_pos_label.setText(QCoreApplication.translate("Widget", u"(0, 0)", None))
        self.centers_l1_ok_button.setText(QCoreApplication.translate("Widget", u"OK", None))
        self.centers_l2_pos_label.setText(QCoreApplication.translate("Widget", u"(0, 0)", None))
        self.centers_l2_ok_button.setText(QCoreApplication.translate("Widget", u"OK", None))
        self.centers_l2_label.setText(QCoreApplication.translate("Widget", u"Relay Lens (L2):", None))
        self.centers_correction_pos_label.setText(QCoreApplication.translate("Widget", u"(0.000, 0.000)", None))
        self.centers_correction_move_button.setText(QCoreApplication.translate("Widget", u"Move", None))
        self.centers_correction_label.setText(QCoreApplication.translate("Widget", u"Correction:", None))
        self.centers_rcpc_pos_label.setText(QCoreApplication.translate("Widget", u"(0, 0)", None))
        self.centers_rcpc_label.setText(QCoreApplication.translate("Widget", u"Red CPC:", None))
        self.centers_gcpc_pos_label.setText(QCoreApplication.translate("Widget", u"(0, 0)", None))
        self.centers_cpc_ok_button.setText(QCoreApplication.translate("Widget", u"OK", None))
        self.centers_gcpc_label.setText(QCoreApplication.translate("Widget", u"Green CPC:", None))
        self.centers_bcpc_pos_label.setText(QCoreApplication.translate("Widget", u"(0, 0)", None))
        self.centers_bcpc_label.setText(QCoreApplication.translate("Widget", u"Blue CPC:", None))
        self.centers_ricg_pos_label.setText(QCoreApplication.translate("Widget", u"(0, 0)", None))
        self.centers_ricg_label.setText(QCoreApplication.translate("Widget", u"Red ICG:", None))
        self.centers_gicg_pos_label.setText(QCoreApplication.translate("Widget", u"(0, 0)", None))
        self.centers_icg_ok_button.setText(QCoreApplication.translate("Widget", u"OK", None))
        self.centers_gicg_label.setText(QCoreApplication.translate("Widget", u"Green ICG:", None))
        self.centers_bicg_pos_label.setText(QCoreApplication.translate("Widget", u"(0, 0)", None))
        self.centers_bicg_label.setText(QCoreApplication.translate("Widget", u"Blue ICG:", None))
        self.centers_rdelta_pos_label.setText(QCoreApplication.translate("Widget", u"0.000000 (mm)", None))
        self.centers_gdelta_pos_label.setText(QCoreApplication.translate("Widget", u"0.000000 (mm)", None))
        self.centers_rdelta_label.setText(QCoreApplication.translate("Widget", u"Red Delta:", None))
        self.centers_bdelta_pos_label.setText(QCoreApplication.translate("Widget", u"0.000000 (mm)", None))
        self.centers_bdelta_label.setText(QCoreApplication.translate("Widget", u"Blue Delta:", None))
        self.centers_gdelta_label.setText(QCoreApplication.translate("Widget", u"Green Delta:", None))
        self.alignment_folder_button.setText(QCoreApplication.translate("Widget", u"...", None))
        self.camera_exposure_val_label.setText(QCoreApplication.translate("Widget", u"160000", None))
        self.camera_gain_val_label.setText(QCoreApplication.translate("Widget", u"0", None))
        self.camera_gamma_val_label.setText(QCoreApplication.translate("Widget", u"1", None))
        self.stage_lensx_entry.setText(QCoreApplication.translate("Widget", u"0.500", None))
        self.stage_lensz_entry.setText(QCoreApplication.translate("Widget", u"0.500", None))
        self.stage_camz_entry.setText(QCoreApplication.translate("Widget", u"0.500", None))
        self.stage_lensy_entry.setText(QCoreApplication.translate("Widget", u"0.500", None))
        self.alignment_folder_entry.setText(QCoreApplication.translate("Widget", default_folder, None))
        self.hardware_stage_indicator.setText("")
        self.hardware_camera_indicator.setText("")
        self.hardware_dc4100_indicator.setText("")
        self.alignment_sn_label.setText(QCoreApplication.translate("Widget", u"Serial Number:", None))
    # retranslateUi
